import type { NextConfig } from "next";

const config: NextConfig = {
  // 1 week cache (604800s) for optimized images generated by Next.js Image Optimization
  images: {
    minimumCacheTTL: 604800,
    remotePatterns: [
      {
        protocol: "https",
        hostname: "lh3.googleusercontent.com",
      },
    ],
  },
  async headers() {
    return [
      {
        // Cache static images, marketing assets, fonts, icons in /public or static extensions for 1 week
        source: "/:path*.(png|jpg|jpeg|gif|webp|svg|ico|woff|woff2)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=604800, stale-while-revalidate=86400",
          },
        ],
      },
      {
        // Cache marketing assets folder specifically for 1 week
        source: "/marketing/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=604800, stale-while-revalidate=86400",
          },
        ],
      },
      {
        // Next.js static build outputs are immutable (1 year)
        source: "/_next/static/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable",
          },
        ],
      },
      {
        // Cache HTML pages at the CDN edge for 60s, stale-while-revalidate for 1 week
        source: "/:path*",
        headers: [
          {
            key: "Cache-Control",
            value:
              "public, max-age=0, s-maxage=60, stale-while-revalidate=604800",
          },
        ],
      },
    ];
  },
};

export default config;
