// Generated by: pnpm --filter @repo/db generate-types
// Run after `supabase start` to regenerate from your local schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          clerk_user_id: string | null;
          email: string | null;
          full_name: string | null;
          role: "admin" | "professor" | "aluno";
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          clerk_user_id?: string | null;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "professor" | "aluno";
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: {
          clerk_user_id?: string | null;
          email?: string | null;
          full_name?: string | null;
          role?: "admin" | "professor" | "aluno";
          avatar_url?: string | null;
        };
        Relationships: [];
      };
      alunos: {
        Row: {
          id: string;
          professor_id: string | null;
          profile_id: string | null;
          plan_id: string | null;
          contact_email: string | null;
          grade: string | null;
          subject_focus: string[] | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          professor_id?: string | null;
          profile_id?: string | null;
          plan_id?: string | null;
          contact_email?: string | null;
          grade?: string | null;
          subject_focus?: string[] | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          professor_id?: string | null;
          profile_id?: string | null;
          plan_id?: string | null;
          contact_email?: string | null;
          grade?: string | null;
          subject_focus?: string[] | null;
          notes?: string | null;
        };
      };
      planos: {
        Row: {
          id: string;
          name: string;
          monthly_amount: number;
          billing_day: number | null;
          description: string | null;
          active: boolean;
          badge: string | null;
          features: string[];
          is_featured: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          monthly_amount: number;
          billing_day?: number | null;
          description?: string | null;
          active?: boolean;
          badge?: string | null;
          features?: string[];
          is_featured?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          name?: string;
          monthly_amount?: number;
          billing_day?: number | null;
          description?: string | null;
          active?: boolean;
          badge?: string | null;
          features?: string[];
          is_featured?: boolean;
          sort_order?: number;
        };
        Relationships: [];
      };
      materiais: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          file_url: string | null;
          subject: string | null;
          grade_level: string | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          file_url?: string | null;
          subject?: string | null;
          grade_level?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          file_url?: string | null;
          subject?: string | null;
          grade_level?: string | null;
          uploaded_by?: string | null;
        };
        Relationships: [];
      };
      financeiro: {
        Row: {
          id: string;
          aluno_id: string | null;
          amount: number;
          due_date: string | null;
          paid_at: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          aluno_id?: string | null;
          amount: number;
          due_date?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          aluno_id?: string | null;
          amount?: number;
          due_date?: string | null;
          paid_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      tarefas: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          due_date: string | null;
          material_id: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          due_date?: string | null;
          material_id?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          due_date?: string | null;
          material_id?: string | null;
          created_by?: string | null;
        };
        Relationships: [];
      };
      tarefa_alunos: {
        Row: {
          id: string;
          tarefa_id: string;
          aluno_id: string;
          status: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes: string | null;
          submission_url: string | null;
          submitted_at: string | null;
          reviewed_at: string | null;
          teacher_feedback: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tarefa_id: string;
          aluno_id: string;
          status?: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes?: string | null;
          submission_url?: string | null;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          teacher_feedback?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tarefa_id?: string;
          aluno_id?: string;
          status?: "pendente" | "em_andamento" | "entregue" | "revisado";
          student_notes?: string | null;
          submission_url?: string | null;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          teacher_feedback?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
